### PR TITLE
General project restructure.

### PR DESCRIPTION
**Pull request by JuaniBattiston**
- Removed duplicated bot constructor.
- Fixed prefix.txt not being used at all.
- Renamed app.py to bot.py (Will make more sense in future prs).
- Minor formatting.

### CODE REVIEW

**Comment by JuaniBattiston** [comment]
These changes are ment as a base for the next pr. Let me know what you think.

**Comment by amanjha8100** [comment]
@Batucho, I will check this out in my local, if everything works fine then will merge this!

**Comment by amanjha8100** [comment]
Hey @Batucho , just one suggestion please do change the bot.py again to app.py as it is related to PROCFILE and documentation related to deployment. It can be changed but few users who don't code are using this and therefore I don't want them to go through the PROCFILE, worker etc. Just look into this point.

**Comment by JuaniBattiston** [comment]
Sure. I'll show you what my idea was with this bot.py file in the next pr. I'll edit this once I finish smt.

**Comment by JuaniBattiston** [comment]
There you go @amanjha8100

**Comment by amanjha8100** [comment]
I will check this out and merge it tomorrow morning!

**Review by amanjha8100 — APPROVED** [review]

**Pull request merged**
